version: '3'
services:
    db:
        image: postgres:13
        container_name: postgresdb
        ports:
            - 5433:5432
        environment:
            LANG: ja_JP.utf8
            POSTGRES_USER: menta
            POSTGRES_PASSWORD: menta
            POSTGRES_DB: mentadb
